database:
  # NOTE: By design, this setting prevents the PGDATABASE environment variable
  # from affecting test runs, so that we don't accidentally affect the
  # production database during testing. If you're not concerned about that and
  # would like to have environment variable overrides, you could instead use
  # something like:
  #
<<<<<<< HEAD
  #   database: "_env:PGDATABASE:yesb_test"
  database: yesb_test
=======
  #   database: "_env:PGDATABASE:yesa_test"
  database: yesa_test
>>>>>>> d003061f74acd3edd0a00b1daf9f6d8a7882dde5

auth-dummy-login: true
